### ISSUE TITLE
Expected one of [luni, lyid, lnsr, clbl, infx, knko, lspf, lclr, shmd, fxrp, LMsk, Lr16, Lr32, Layr, Mt16, Mt32, Mtrn, Alph, FMsk, lnk2, FEid, FXid, PxSD, lnk3, lnkD, cinf, lrFX, tySh, TySh, lfx2, Txt2, Patt, Pat2, Pat3] but found [80, 108, 76, 100] PlLd

### ISSUE THREAD

**Issue by hezhikang** [Minecraftian14/JPSD#1]

**Comment by hezhikang** [comment]
try {
			 PSDDocument document = new PSDDocument(new File("D:\\Java环境\\单框.psd"));
			 BufferedImage image = document.getCompositeImage();
			 
			 
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}

**Comment by Minecraftian14** [comment]
Heya [hezhikang](https://github.com/hezhikang)!
Thanks for letting me know of this problem 😄.

I'll fix this issue today 👍

**Comment by Minecraftian14** [comment]
@hezhikang,
I have made some changes to the project in order to solve this issue.
Please try adding this dependency and test if your PSD file can be opened:
```gradle
dependencies {
  implementation 'in.mcxiv:JPSD:905552f764'
}
```

In case you are not using gradle, please refer [Jitpack](https://jitpack.io/#in.mcxiv/JPSD/905552f764).

It will be really helpful if you can provide me a PSD file which yields these errors.

Thanks a lot 😄.
